import type { Equipment, Student } from "./types"

export const initialEquipment: Equipment[] = [
  {
    id: "eq-001",
    name: "Laptop Dell XPS 13",
    status: "available",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Electronics",
    owner: "IT Department",
    location: "Room 101",
    room: 1,
    building: 1,
    lab: 1,
  },
  {
    id: "eq-002",
    name: "Projector Epson",
    status: "available",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Electronics",
    owner: "IT Department",
    location: "Room 101",
    room: 1,
    building: 1,
    lab: 1,
  },
  {
    id: "eq-003",
    name: 'iPad Pro 12.9"',
    status: "available",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Electronics",
    owner: "IT Department",
    location: "Room 101",
    room: 2,
    building: 1,
    lab: 1,
  },
  {
    id: "eq-004",
    name: "Digital Camera Canon",
    status: "available",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Electronics",
    owner: "IT Department",
    location: "Room 101",
    room: 2,
    building: 1,
    lab: 2,
  },
  {
    id: "eq-005",
    name: "Microscope",
    status: "available",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Electronics",
    owner: "IT Department",
    location: "Room 101",
    room: 1,
    building: 2,
    lab: 1,
  },
  {
    id: "eq-006",
    name: "VR Headset",
    status: "available",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Electronics",
    owner: "IT Department",
    location: "Room 101",
    room: 1,
    building: 2,
    lab: 2,
  },
]

export const initialStudents: Student[] = [
  {
    id: "st-001",
    name: "Anna Petrova",
    group: "CS-101",
    hasAccess: true,
  },
  {
    id: "st-002",
    name: "Ivan Ivanov",
    group: "CS-101",
    hasAccess: true,
  },
  {
    id: "st-003",
    name: "Maria Sidorova",
    group: "CS-102",
    hasAccess: false,
  },
  {
    id: "st-004",
    name: "Alexey Smirnov",
    group: "CS-102",
    hasAccess: true,
  },
  {
    id: "st-005",
    name: "Elena Volkova",
    group: "CS-103",
    hasAccess: true,
  },
]

